# Generated by Django 3.0.5 on 2020-07-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_homepage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
