# Generated by Django 3.0.5 on 2020-07-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200705_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='Project', max_length=100),
        ),
    ]
