# Generated by Django 3.0.5 on 2020-07-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200705_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='summary',
            field=models.TextField(),
        ),
    ]
