# Generated by Django 3.0.5 on 2020-07-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200705_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='complete',
            field=models.TextField(default=models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='summary',
            field=models.CharField(max_length=200),
        ),
    ]
